name: aprendiendo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  beauty_textfield: ^0.0.1
  bouncing_widget: ^1.2.0
  dropdown_formfield: ^0.1.3
  date_time_picker: "^1.1.1"
  gender_picker: ^1.0.4
  extended_tabs: ^1.0.1
  custom_switch: ^0.0.1
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  fluttertoast: ^7.1.6
  flutter_map: ^0.10.1+1
  flutter_map_tappable_polyline: ^1.2.0
  latlng: ^0.0.2
  qr_code_scanner: ^0.3.5
  flutter_verification_code: ^0.2.1
  flutter_local_notifications: ^4.0.1
  rxdart: ^0.24.0
  flutter_blue: ^0.7.2
  beacon_broadcast: ^0.2.2
  uuid: 2.2.2
  flutter_native_splash: ^0.3.0
  hexcolor: ^2.0.0
  flutter_svg: ^0.19.1
  permission_handler: ^5.1.0+2
  contacts_service: ^0.4.6
  direct_select: "^1.0.0"
  geolocator: ^6.2.0




  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/Marca_png/iconoApp_CoVIDAlert_negativo.png
  - assets/Marca_png/iconoApp_CoVIDAlert_positivo.png
  - assets/Marca_png/Logo_CoVIDAlert_negativo.png
  - assets/Marca_png/Logo_CoVIDAlert_positivo.png
  - assets/Marca_png/Logosímbolo lateral_UN-Blanco.png
  - assets/Marca_png/Logosímbolo lateral_UN-CoVIDAlert.png
  - assets/Marca_png/mapa_manizales.png
  - assets/Marca_png/mapa_manizales_barra.png
  - assets/Marca_png/grafo.png
  - assets/Marca_png/mapa_manizales_barraHori.png
  - assets/jsons/geomapManizales.json
  - assets/Imagenes_assetspng/logos/logo_apertura.png
  - assets/Imagenes_assetspng/logos/logos_apertura.png
  - assets/Imagenes_assetspng/logos/textura_apertura.png
  - assets/Imagenes_assets_svg/iconos/contagio_comunas_off.svg
  - assets/Imagenes_assets_svg/iconos/inicio_off.svg
  - assets/Imagenes_assets_svg/iconos/red_contactos_off.svg
  - assets/Imagenes_assets_svg/iconos/vacuna_off.svg
  - assets/Imagenes_assets_svg/iconos/reportar_off.svg
  - assets/Imagenes_assets_svg/qr/qr.svg
  - assets/Imagenes_assetspng/íconos/contagio_comunas_off.png
  - assets/Imagenes_assetspng/íconos/inicio_off.png
  - assets/Imagenes_assetspng/íconos/red_contactos_off.png
  - assets/Imagenes_assetspng/íconos/reportar_off.png
  - assets/Imagenes_assetspng/íconos/vacuna_off.png
  - assets/Imagenes_assetspng/qr/qr.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: laca
      fonts:
        - asset: fonts/Laca Black Italic.otf
        - asset: fonts/Laca Black.otf
        - asset: fonts/Laca Bold Italic.otf
        - asset: fonts/Laca Bold.otf
        - asset: fonts/Laca Book Italic.otf
        - asset: fonts/Laca Book.otf
        - asset: fonts/Laca ExtraLight Italic.otf
        - asset: fonts/Laca ExtraLight.otf
        - asset: fonts/Laca Light Italic.otf
        - asset: fonts/Laca Light.otf
        - asset: fonts/Laca Medium Italic.otf
        - asset: fonts/Laca Medium.otf
        - asset: fonts/Laca Regular Italic.otf
        - asset: fonts/Laca Regular.otf
        - asset: fonts/Laca Semibold Italic.otf
        - asset: fonts/Laca Semibold.otf
        - asset: fonts/FiraSans-ExtraBold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf


    #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  